language: node_js
node_js:
- '7'
cache: yarn
notifications:
  email: false
  slack:
    secure: Vqw9JthYaL+lHGA1Yll5GSn26QEa8r1EXlZ5XrZQiWJiacWPKIboBpRmajEkndwn3J/bvsQpXLSeLqPGxo0IIbOZczxUftT2GifBSw/HGYrZuP2OQmY5DgtoHCQuJFWqBZHLJmvkHdHxKbb9yFJAD3BVsaV0h5vJAr3f7spXA55Q/Y6683SIst/7CeVWwNJLYrFU/DmQv125b2ClLxrsA3QmO/BE5YgCAy0xZGBEOWsyPO0cLuCyYr9aJ21VuoYzryaz53Dw/mE+Xqwk8wDenadFqj6AHI9FfQCylHAjXSv9YBc+FQxO2JEZ0k4Yw97b016nIly4fIC5BdO/D/BWSBEYwUkw0xohZeCEvF9mhcA7x8b4iJ0Wy6jCBH3beW4aeaeCb4UR8LhSIpkgosTMKeoubHJ4gkOAzVIbn7DG1NlKB/QK+LeYS1aPOtUV1qW5yTS3pdy1eFvAy32x6CyuOM70v3kTvVVzBLfJmXVp9N65C32qWG/H7QK5qEPj6SW0SSb6XVz/MnqwuPhZDjzHZANost07rKEtTp6ll5/SKl5vrhl8Oqxap/k1a0KTDNFDWZrxqlvt8pfbX1AUQBtwIAZSxyQtxSQcjNgFtcxOrAgyRIdQWYX48ciC40XZV4clu4OapJZyGi0CHegK1bX4bjIt2NgXOzdXxBhJtDSEN3A=

script:
- 'npm run build && npm test'